name: Run Amazon Ranking Script

on:
#  schedule:
#    - cron: "0 21,5,13 * * *"  # 日本時間の 6時, 14時, 22時 に相当
  workflow_dispatch:  # 手動でも実行可能

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Python script
        run: |
          python main.py
